# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MikeTineo.com
email: miketineo@gmail.com
description: >
  Hi there, welcome to my website this is meant to show some of my life latest
  relevant events, why is that important? I dont know  but Im gonna post that here
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://miketineo.com" # the base hostname & protocol for your site
twitter_username: miketineo
github_username:  miketineo

# Build settings
markdown: kramdown
